server:
  port: 5005
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: apigateway-service
#  cloud:
#    gateway:
#      routes:
#        - id: first-service
#          uri: http://localhost:5000/
#          predicates: #??
#            - Path=/first-service/**
#        - id: second-service
#          uri: http://localhost:5002/
#          predicates: #??
#            - Path=/second-service/**